version: '3.3'
services:
  xanny-mysql:
    image: mysql:8.0    # 使用镜像 mysql：5.7版本
    container_name: xanny-mysql
    hostname: xannymysql
    restart: always
    ports:
        - '3309:3306'
    volumes:
        - ./etc/db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: S67xWdwEqW
      MYSQL_RANDOM_ROOT_PASSWORD: S67xWdwEqW

  xanny-wordpress:
    image: wordpress
    container_name: xanny-wordpress
    restart: always
    ports:
        - '9090:9000'
        - '88:80'
    volumes:
        - ./etc/wordpress:/var/www/html
    environment:
        WORDPRESS_DB_HOST: xannymysql:3306
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: S67xWdwEqW
    depends_on:
        - xanny-mysql
